export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited Transaction  with zero fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charge any fees.",
    buttonLabel: "Get Started",
    imgStart: false,
    img: ("../../images/svg_1.svg"),
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Unlimited Access",
    headLine: "Login to your account at anytime",
    description: "We have you covered no matter where you are located. All you need is an internet connection and a phone or computer",
    buttonLabel: "Learn More",
    imgStart: true,
    img: ("../../images/svg-2.svg"),
    alt: "piggybank",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "join our team",
    headLine: "Creating an account is extemely easy",
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your informationand you're ready to go.",
    buttonLabel: "Start Now",
    imgStart: true,
    img: require("../../images/svg-3.svg"),
    alt: "paper",
    dark: false,
    primary: false,
    darkText: true,
}
