export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited Transaction  with zero fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charge any fees.",
    buttonLabel: "Get Started",
    imgStart: false,
    img: ("../../images/svg_1.svg"),
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited Transaction  with zero fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charge any fees.",
    buttonLabel: "Get Started",
    imgStart: false,
    img: ("../../images/svg-2.svg"),
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    headLine: "Unlimited Transaction  with zero fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charge any fees.",
    buttonLabel: "Get Started",
    imgStart: false,
    img: require("../../images/svg-3.svg"),
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
}
